
import { SiteAnalysis, WCAGIssue, SEOIssue } from "./types";

export const wcagIssuesMock: WCAGIssue[] = [
  {
    id: "1.1.1_img_alt",
    criterion: "1.1.1 Non-text Content",
    level: "A",
    description: "Images do not have alternative text",
    impact: "serious",
    element: "<img src='banner.jpg'>",
    location: "Header section",
    remediation: "Add descriptive alt attributes to all images",
  },
  {
    id: "1.3.1_form_labels",
    criterion: "1.3.1 Info and Relationships",
    level: "A",
    description: "Form inputs do not have associated labels",
    impact: "serious",
    element: "<input type='text' name='search'>",
    location: "Search form",
    remediation: "Add proper <label> elements or aria-label attributes",
  },
  {
    id: "1.4.3_contrast",
    criterion: "1.4.3 Contrast (Minimum)",
    level: "AA",
    description: "Text contrast ratio is below 4.5:1",
    impact: "serious",
    element: "<p style='color: #999'>Light gray text</p>",
    location: "Footer section",
    remediation: "Increase contrast to at least 4.5:1 for normal text",
  },
  {
    id: "2.1.1_keyboard",
    criterion: "2.1.1 Keyboard",
    level: "A",
    description: "Custom dropdown cannot be operated with keyboard",
    impact: "critical",
    element: "<div class='custom-dropdown'>",
    location: "Navigation menu",
    remediation: "Implement keyboard navigation with appropriate ARIA roles",
  },
  {
    id: "2.4.4_link_purpose",
    criterion: "2.4.4 Link Purpose (In Context)",
    level: "A",
    description: "Links do not have descriptive text",
    impact: "moderate",
    element: "<a href='p1.html'>Click here</a>",
    location: "Main content",
    remediation: "Use descriptive link text that indicates the purpose",
  },
  {
    id: "3.3.2_form_labels",
    criterion: "3.3.2 Labels or Instructions",
    level: "A",
    description: "Required fields are not indicated",
    impact: "moderate",
    element: "<input type='text' name='email'>",
    location: "Contact form",
    remediation: "Use aria-required or visually indicate required fields",
  },
  {
    id: "4.1.2_name_role_value",
    criterion: "4.1.2 Name, Role, Value",
    level: "A",
    description: "Custom buttons do not have accessible names",
    impact: "serious",
    element: "<div onclick='submitForm()'>Submit</div>",
    location: "Form submission",
    remediation: "Use proper button elements or add ARIA attributes",
  },
  {
    id: "1.4.10_reflow",
    criterion: "1.4.10 Reflow",
    level: "AA",
    description: "Content is lost when zoomed to 400%",
    impact: "serious",
    location: "Entire page",
    remediation: "Implement responsive design that works at 400% zoom",
  },
  {
    id: "1.4.11_non_text_contrast",
    criterion: "1.4.11 Non-text Contrast",
    level: "AA",
    description: "UI components have insufficient contrast",
    impact: "moderate",
    element: "<button style='border: 1px solid #ccc'>",
    location: "Form buttons",
    remediation: "Ensure UI elements have at least 3:1 contrast ratio",
  },
  {
    id: "1.2.5_audio_description",
    criterion: "1.2.5 Audio Description (Prerecorded)",
    level: "AA",
    description: "Video content lacks audio descriptions",
    impact: "serious",
    element: "<video src='product-demo.mp4'>",
    location: "Products page",
    remediation: "Provide audio descriptions for video content",
  },
];

export const seoIssuesMock: SEOIssue[] = [
  {
    id: "meta_title_length",
    category: "meta",
    description: "Title tag is too short (15 characters)",
    impact: "high",
    remediation: "Make title between 50-60 characters with primary keywords",
  },
  {
    id: "meta_description_missing",
    category: "meta",
    description: "Meta description is missing",
    impact: "high",
    remediation: "Add a compelling meta description between 120-158 characters",
  },
  {
    id: "h1_missing",
    category: "structure",
    description: "Page is missing H1 tag",
    impact: "high",
    remediation: "Add a single H1 tag containing primary keyword",
  },
  {
    id: "img_alt_seo",
    category: "content",
    description: "Images missing alt text with keywords",
    impact: "medium",
    remediation: "Add descriptive alt text with relevant keywords to images",
  },
  {
    id: "mobile_responsive",
    category: "technical",
    description: "Page is not mobile-friendly",
    impact: "high",
    remediation: "Implement responsive design for all device sizes",
  },
  {
    id: "slow_page_speed",
    category: "technical",
    description: "Page load time exceeds 3 seconds",
    impact: "high",
    remediation: "Optimize images, minify CSS/JS, and implement caching",
  },
  {
    id: "keyword_density",
    category: "content",
    description: "Low keyword density in content (0.5%)",
    impact: "medium",
    remediation: "Increase keyword usage naturally to 1-2% of content",
  },
  {
    id: "broken_links",
    category: "technical",
    description: "Page contains 3 broken links",
    impact: "medium",
    remediation: "Fix or remove broken links to improve user experience",
  },
  {
    id: "url_structure",
    category: "structure",
    description: "URL contains unnecessary parameters",
    impact: "medium",
    remediation: "Create clean, keyword-rich URLs without parameters",
  },
  {
    id: "canonical_missing",
    category: "technical",
    description: "Canonical tag is missing",
    impact: "medium",
    remediation: "Add canonical tags to prevent duplicate content issues",
  },
];

export const mockAnalysis: SiteAnalysis = {
  url: "https://example.com",
  scanDate: new Date().toISOString(),
  accessibilityScore: {
    overall: 72,
    wcagA: 68,
    wcagAA: 76,
    wcagAAA: 45,
    issuesByImpact: {
      critical: 2,
      serious: 5,
      moderate: 8,
      minor: 3,
    },
  },
  seoScore: {
    overall: 78,
    meta: 65,
    content: 82,
    technical: 74,
    structure: 88,
  },
  accessibilityIssues: wcagIssuesMock,
  seoIssues: seoIssuesMock,
  assistiveTechnologies: {
    screenReaders: true,
    keyboardNavigation: false,
    voiceControl: false,
    magnification: true,
  },
  wcagCompliance: {
    conformanceLevel: "A",
    passedCriteria: ["1.2.1", "1.2.2", "1.3.2", "2.2.1", "2.2.2"],
    failedCriteria: ["1.1.1", "1.3.1", "1.4.3", "2.1.1", "2.4.4"],
  },
};
